#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     lite,           sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          leftWheel,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightWheel,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Chase function
void Chase()
{
	motor(leftWheel)=SensorValue(lite);
	motor(rightWheel)=SensorValue(lite);
	wait1Msec(1000);
}

// Purring sound
void Purr()
{
	PlaySound(soundLowBuzz);
	wait1Msec(1000);
}

task main()
{
	int soundReading;
	int touchReading;
	int choice;
	int range;
	int startled;
	int pets;
	int ignore;

	ClearTimer(T1);
	ClearTimer(T2);
	ClearTimer(T3);

	while(true){      //Stay away from walls while performing Chase function
		if (SensorValue(sonar)>10){ //If distance greater than 10 continue Chase
			Chase ();
		}
		else { //If distance less than 10 turn to right
			motor(leftWheel)=80;
			motor(rightWheel)=10;
			wait1Msec(1000);
		}
	}
	while (true) {   //Reacting to sound

		// get the time in increments of 100ms
		startled = time100(T1);
		pets = time100(T2);
		ignore = time100(T3);

		// get the overall range of time elapsed and generate
		// a random number based on that choice
		range = startled + pets + ignore;
		choice = random(range);

		nxtDisplayTextLine(1, "timers: %i %i %i", startled, pets, ignore);

		// choose between 3 actions. if its been awhile since one of the actions occurred,
		// this decision rule will tend to choose that action. After the action is chosen,
		// clear the timer to start counting at zero. That will make this action not likely
		// to repeat.

		soundReading = SensorValue(sound);	// get the current reading from the sound sensor
		touchReading = SensorValue(touch);	// get the current reading from the touch sensor
		if (soundReading>60){   //If loud sound choose between actions


			if (choice < startled) { //Run away from sound
				nxtDisplayTextLine(2, "startled");
				motor(leftWheel) = 100;
				motor(rightWheel) = 100;
				wait1Msec(2000);
				ClearTimer(T1);
			}
			else if (choice < startled+pets) { //Likes sound, responds with purring
				nxtDisplayTextLine(2, "pets");
				Purr();
				wait1Msec(2000);
				ClearTimer(T2);
			}
			else { //Ignore sound and continue Chase
				nxtDisplayTextLine(2, "ignore");
				Chase();
				wait1Msec(2000);
				ClearTimer(T3);
			}

		}
		else {  //if no loud sound, continue chase function
			Chase();
			wait1Msec(100);
		}
	}
}
